[target.x86_64-pc-windows-msvc]
# Windows-specific optimizations
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=/LTCG",  # Link-time code generation on Windows
]

[target.x86_64-unknown-linux-gnu]
# Linux-specific optimizations
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-fuse-ld=lld",  # Use faster linker if available
]

# Incremental compilation for faster dev builds
[profile.dev]
incremental = true

# Optimize dependencies even in dev mode
[profile.dev.package."*"]
opt-level = 2

# Net settings to reduce download times
[net]
git-fetch-with-cli = false

# Registry settings
[registries.crates-io]
protocol = "sparse"
